unbind C-b
set -g prefix C-j
bind C-j send-prefix
bind h swap-window -t -1

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection

# 边框颜色
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39
# 标题内容
set -g pane-border-format "#{?pane_active,#[bold],}#{pane_index} #{pane_current_command} #[fg=colour244](#{b:pane_current_path})"

set-window-option -g pane-border-status off
set-hook -g after-split-window \
    'set-window-option pane-border-status top'
# set-hook -g after-kill-pane \
#     'if-shell -F "#{==:#{window_panes},1}" \
#         "set-window-option pane-border-status off"'
set-hook -g pane-exited \
    'if-shell -F "#{==:#{window_panes},1}" \
        "set-window-option pane-border-status off"'
