unbind C-b
set -g prefix C-j
bind C-j send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection

